#!/bin/bash -x
#
# Copyright (c) 2017 Mellanox Technologies. All rights reserved.
#
# This Software is licensed under one of the following licenses:
#
# 1) under the terms of the "Common Public License 1.0" a copy of which is
#    available from the Open Source Initiative, see
#    http://www.opensource.org/licenses/cpl.php.
#
# 2) under the terms of the "The BSD License" a copy of which is
#    available from the Open Source Initiative, see
#    http://www.opensource.org/licenses/bsd-license.php.
#
# 3) under the terms of the "GNU General Public License (GPL) Version 2" a
#    copy of which is available from the Open Source Initiative, see
#    http://www.opensource.org/licenses/gpl-license.php.
#
# Licensee has the right to choose one of the above licenses.
#
# Redistributions of source code must retain the above copyright
# notice and one of the license notices.
#
# Redistributions in binary form must reproduce both the above copyright
# notice, one of the license notices in the documentation
# and/or other materials provided with the distribution.
#

DEST_DIR=$1

install -d ${DEST_DIR}/etc/infiniband
if [ ! -s ${DEST_DIR}/etc/infiniband/openib.conf ]; then
	install -m 0644 ofed_scripts/openib.conf ${DEST_DIR}/etc/infiniband
fi
if [ ! -s ${DEST_DIR}/etc/infiniband/mlx5.conf ]; then
	install -m 0644 ofed_scripts/mlx5.conf ${DEST_DIR}/etc/infiniband
fi

while read line
do
	item=$(echo "$line" | sed -e 's/=.*//g')
	if [ "X$item" != "X" ] && ! (grep -q "$item" ${DEST_DIR}/etc/infiniband/openib.conf 2>/dev/null); then
		echo "$line" >> ${DEST_DIR}/etc/infiniband/openib.conf
	fi
done < "ofed_scripts/openib.conf.tmp"
