#!/bin/sh
#
# Copyright (c) 2017 Mellanox Technologies. All rights reserved.
#
# This Software is licensed under one of the following licenses:
#
# 1) under the terms of the "Common Public License 1.0" a copy of which is
#    available from the Open Source Initiative, see
#    http://www.opensource.org/licenses/cpl.php.
#
# 2) under the terms of the "The BSD License" a copy of which is
#    available from the Open Source Initiative, see
#    http://www.opensource.org/licenses/bsd-license.php.
#
# 3) under the terms of the "GNU General Public License (GPL) Version 2" a
#    copy of which is available from the Open Source Initiative, see
#    http://www.opensource.org/licenses/gpl-license.php.
#
# Licensee has the right to choose one of the above licenses.
#
# Redistributions of source code must retain the above copyright
# notice and one of the license notices.
#
# Redistributions in binary form must reproduce both the above copyright
# notice, one of the license notices in the documentation
# and/or other materials provided with the distribution.
#

for python in python python3 python2 false; do
	if which $python >/dev/null 2>&1; then
		break
	fi
case "$python" in *false)
	echo "No python on the system. Aborting"
	;;
esac

# prepare source tgz
$python setup.py sdist

# prepare spec file
$python setup.py bdist_rpm  --spec-only
sed -i "s/BuildArch/#BuildArch/" dist/ofed-le-utils.spec

# prepare src rpm
rpmbuild --define '_sourcedir dist/' --define '_srcrpmdir dist/'  -bs dist/ofed-le-utils.spec
